In [1]:
#import libraries
import os
import pandas as pd
import numpy as np
import scipy as sp
import seaborn as sns
import math as m
import xlrd
from scipy import stats
from sklearn import datasets
import matplotlib.pyplot as plt

In [2]:
path = os.getcwd()

In [3]:
itrain = pd.read_excel(str(path)+'/Wine_dataset.xlsx')

In [4]:
df = itrain[['Alcohol', 'Malic_Acid', 'Ash', 'Magnesium','Color_Intensity']]
df.head()

Alcohol  Malic_Acid   Ash  Magnesium  Color_Intensity
0    14.23        1.71  2.43        127             5.64
1    13.20        1.78  2.14        100             4.38
2    13.16        2.36  2.67        101             5.68
3    14.37        1.95  2.50        113             7.80
4    13.24        2.59  2.87        118             4.32

In [5]:
### Standarization:
from sklearn.preprocessing import StandardScaler
# Standardizing the features
df_std = StandardScaler().fit_transform(df)

In [6]:
cov_mat = np.cov(df_std.T)
print('\nNumPy covariance matrix:\n', cov_mat)

eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('\nEigenvectors \n %s' %eig_vecs)
print('\nEigenvalues \n %s' %eig_vals)


NumPy covariance matrix:
 [[ 1.00564972  0.09493026  0.21273976  0.27232816  0.549451  ]
 [ 0.09493026  1.00564972  0.16497228 -0.05488343  0.25039204]
 [ 0.21273976  0.16497228  1.00564972  0.28820583  0.2603499 ]
 [ 0.27232816 -0.05488343  0.28820583  1.00564972  0.20107967]
 [ 0.549451    0.25039204  0.2603499   0.20107967  1.00564972]]

Eigenvectors 
 [[-0.5428004  -0.66849427  0.09760709 -0.49568925  0.05699265]
 [-0.24892712 -0.17289972 -0.45924128  0.32699208 -0.76831934]
 [-0.42503992 -0.0691627   0.58042254  0.68421723  0.09753991]
 [-0.38075751  0.08463007 -0.6555143   0.24265061  0.59940234]
 [-0.56370896  0.71503522  0.11393411 -0.34689453 -0.19401041]]

Eigenvalues 
 [1.97741586 0.43003237 0.6365092  0.90058247 1.08370868]


In [7]:
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort(key=lambda x: x[0], reverse=True)

print(eig_pairs)

# Visually confirm that the list is correctly sorted by decreasing eigenvalues
print('\nEigenvalues in descending order:')
for i in eig_pairs:
    print(i[0])

[(1.9774158603195886, array([-0.5428004 , -0.24892712, -0.42503992, -0.38075751, -0.56370896])), (1.0837086804729743, array([ 0.05699265, -0.76831934,  0.09753991,  0.59940234, -0.19401041])), (0.9005824712451571, array([-0.49568925,  0.32699208,  0.68421723,  0.24265061, -0.34689453])), (0.6365092011456471, array([ 0.09760709, -0.45924128,  0.58042254, -0.6555143 ,  0.11393411])), (0.43003237438725506, array([-0.66849427, -0.17289972, -0.0691627 ,  0.08463007,  0.71503522]))]

Eigenvalues in descending order:
1.9774158603195886
1.0837086804729743
0.9005824712451571
0.6365092011456471
0.43003237438725506


In [8]:
matrix_w = np.hstack((eig_pairs[0][1].reshape(5,1),
                      eig_pairs[1][1].reshape(5,1)))

print('Matrix W:\n', matrix_w)

Y = df_std.dot(matrix_w)
print('\n Final Y:\n', Y)

Matrix W:
 [[-0.5428004   0.05699265]
 [-0.24892712 -0.76831934]
 [-0.42503992  0.09753991]
 [-0.38075751  0.59940234]
 [-0.56370896 -0.19401041]]

 Final Y:
 [[-1.65360469  1.6395351 ]
 [ 0.50100193  0.38476653]
 [-0.76895434  0.10388225]
 [-2.06228281  0.73834467]
 [-1.3075769   0.85179158]
 [-1.5453881   0.88562408]
 [-0.90384987  0.27564213]
 [-1.61332508  1.18527833]
 [-0.72699241  0.41169827]
 [-0.68646874  0.45163552]
 [-0.9036857   0.33854675]
 [-0.34599598  0.45815803]
 [-0.27950383 -0.01109468]
 [-0.92363263  0.15313221]
 [-1.49744182  0.31366952]
 [-1.69690483  0.85398861]
 [-2.14744062  1.26142572]
 [-1.56259565  1.19007583]
 [-1.91586404  0.68086978]
 [-1.34483178  0.26804911]
 [-1.26439739  1.58633577]
 [-0.64443621 -0.77148196]
 [-0.08594193  0.53469627]
 [ 0.42890711  0.44709172]
 [-0.12043278  0.45660032]
 [-1.58326133  1.65025793]
 [-0.28519309  0.24632964]
 [ 0.71261714  0.21675883]
 [-1.21686942  0.86902116]
 [-0.10631423  0.34122293]
 [-1.01045818  0.7461637 ]
 [-0